2018-01-30 17:41:55,486 ERROR: Exception on /student/cat/teacher_info [GET] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 407, in student_cat_teacher_info
    teacher = Teacher.query.get(student.s_teacher_id)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 871, in get
    ident, loading.load_on_ident)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 882, in _get_impl
    if len(ident) != len(mapper.primary_key):
TypeError: object of type 'NoneType' has no len()
2018-01-31 16:03:54,811 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-01-31 17:48:40,601 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 440, in teacher_release_class_info
    teacher_arrange_classes(data, Week_list, teacher.id)
AttributeError: 'BaseQuery' object has no attribute 'id'
2018-01-31 19:05:11,236 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 440, in teacher_release_class_info
    teacher_arrange_classes(data, Week_list, teacher.id)
  File "/home/signit/桌面/Graduation design/main/model/__init__.py", line 202, in teacher_arrange_classes
    class_am_11.class_am = data['am_1']
AttributeError: 'NoneType' object has no attribute 'class_am'
2018-01-31 19:10:14,444 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 440, in teacher_release_class_info
    teacher_arrange_classes(data, Week_list, teacher.id)
  File "/home/signit/桌面/Graduation design/main/model/__init__.py", line 202, in teacher_arrange_classes
    class_am_11.class_am = data['am_1']
AttributeError: 'NoneType' object has no attribute 'class_am'
2018-01-31 19:10:24,238 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 440, in teacher_release_class_info
    teacher_arrange_classes(data, Week_list, teacher.id)
  File "/home/signit/桌面/Graduation design/main/model/__init__.py", line 202, in teacher_arrange_classes
    class_am_11.class_am = data['am_1']
AttributeError: 'NoneType' object has no attribute 'class_am'
2018-01-31 19:10:32,036 ERROR: Exception on /teacher/release_class_info [POST] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/signit/桌面/Graduation design/main/routes.py", line 440, in teacher_release_class_info
    teacher_arrange_classes(data, Week_list, teacher.id)
  File "/home/signit/桌面/Graduation design/main/model/__init__.py", line 202, in teacher_arrange_classes
    class_am_11.class_am = data['am_1']
AttributeError: 'NoneType' object has no attribute 'class_am'
2018-01-31 20:37:56,696 ERROR: Exception on /teacher/cancel_car/1 [GET] [in /usr/local/lib/python3.5/dist-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
